apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

configMapGenerator:
  - name: fog-profile-override
    namespace: fog-system
    literals:
      - profile_id=single-home-demo
      - mode=single-home
      - posture_state=local_operational
generatorOptions:
  disableNameSuffixHash: true
