apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

configMapGenerator:
  - name: fog-profile-override
    namespace: fog-system
    literals:
      - profile_id=regional-multimesh-demo
      - mode=regional-multimesh
      - posture_state=fleet_managed
generatorOptions:
  disableNameSuffixHash: true
